version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - '6500:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  backend:
    depends_on:
      - db
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend
    command: "make start"
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    restart: "no"
volumes:
  db_volume:
    driver: local



