"""first

Revision ID: 5c504711c5cc
Revises: d5ecaa15f8dd
Create Date: 2023-12-10 20:46:53.200818

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c504711c5cc"
down_revision: Union[str, None] = "d5ecaa15f8dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "owners", "birthday", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "owners", "birthday", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
