"""fourth

Revision ID: 885c01bf428f
Revises: ec304018f349
Create Date: 2023-12-10 21:19:20.486109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885c01bf428f'
down_revision: Union[str, None] = 'ec304018f349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'properties', ['code_internal'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='unique')
    # ### end Alembic commands ###
