"""second

Revision ID: ad67f199cae7
Revises: 5c504711c5cc
Create Date: 2023-12-10 20:55:50.317913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad67f199cae7'
down_revision: Union[str, None] = '5c504711c5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('dni', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'owners', ['dni'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='unique')
    op.drop_column('owners', 'dni')
    # ### end Alembic commands ###
